### ISSUE TITLE
Please consider adding an open-source license

### ISSUE THREAD

**Issue by xenotropic** [Ethan3600/USPTO-Trademark-API#2]
Without a license, this is still copyrighted, proprietary code. I'd like to work on something that uses this, but would want it to be under some sort of open source license first - MIT or GPLv3 would seem most logical.

**Comment by Ethan3600** [comment]
Just added one! I'll admit, I haven't looked at this repo in a long time! It most definitely needs to be updated. At the time of writing, I was just starting to learn to code.
